Some helper scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -16,5 +16,8 @@ if [ -n "$HDD_2" ]; then
 	HDD_2="${HDD_2##*/}"
 	set -- NUMDISKS=2 "HDD_2=$HDD_2" "$@"
 fi
-cd autoinst
+pushd autoinst >/dev/null
 isotovideo CASEDIR="$CASEDIR" DISTRI="$DISTRI" HDD_1="${hdd##*/}" UEFI=1 ARCH="$(uname -m)" "$@"
+echo "### Exit code: $?, results:"
+popd >/dev/null
+./eval
